#!/bin/sh
########################################################################
# Begin fcron
#
# Description : deluge-web script
#
#
########################################################################

### BEGIN INIT INFO
# Provides:            deluge-web
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/bin/deluge-web"

#$LastChangedBy: dj $
#$Date: 2019-09-08 13:50:13 -0500 (Sun, 08 Sep 2019) $

case "$1" in
   start)
      log_info_msg "Starting deluge-web..."
      start_daemon ${BIN_FILE} --pidfile /home/deluge/deluged-web.pid -L info -l /home/deluge/deluged-web.log --user deluge --group deluge --config /home/deluge/.config/deluge --logfile /var/log/deluge-web.log
      evaluate_retval
      ;;

   stop)
      	log_info_msg "Stopping deluge-web..."
	if [ -f /home/deluge/deluged-web.pid ]; then
          PID_FILE=$(cat /home/deluge/deluged-web.pid)
          kill -9 $PID_FILE
        else
          echo "Deluged is not running."
        fi
        #rm -rf /home/deluge/deluge-web.pid
        evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc ${BIN_FILE}
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/fcron
