[llvm]
link-shared = true

[build]
target = ["i686-unknown-linux-gnu"] # defaults to just the build triple
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
python = "python"
extended = true
sanitizers = false
profiler = true
local-rebuild = true

[install]
prefix = "/usr"

[rust]
# 0 or the new default of 16 is faster, but can result in worse performance
# https://github.com/rust-lang/rust/issues/47745
codegen-units = 1

debuginfo-level = 2

channel = "stable"

rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
